[template]
src = "production.tmpl"
dest = "/config/production.json"
keys = [
    "/configuration/logger/level",
    "/configuration/db/service/url",
    "/configuration/db/max/retries",
    "/configuration/storage/engine",
    "/configuration/fs/export/directory",
    "/configuration/batch/size",
    "/configuration/file/formats",
    "/configuration/s3/api/version",
    "/configuration/s3/endpoint",
    "/configuration/s3/access/key/id",
    "/configuration/s3/secret/access/key",
    "/configuration/s3/max/retries",
    "/configuration/s3/ssl",
    "/configuration/s3/bucket"
]
